<?php

/**
 * @file
 * Contains islandora_group_defaults.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_group_defaults_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_group_defaults module.
    case 'help.page.islandora_group_defaults':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Default config for Access controle with Group, Group Media') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function islandora_group_defaults_theme() {
  return [
    'islandora_group_defaults' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_modules_installed
 */
function islandora_group_defaults_modules_installed($modules) {
    if (in_array('islandora_group_defaults', $modules)) {
        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'collection_based']);
        $group_to_create->set('label', 'Public Collection');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();

        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'collection_based']);
        $group_to_create->set('label', 'Private Collection');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();

        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'role_based']);
        $group_to_create->set('label', 'Private');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();

        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'collection_based']);
        $group_to_create->set('label', 'Public');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();
    }
}

/**
 * Implements hook_entity_insert
 */
function islandora_group_defaults_entity_insert(\Drupal\Core\Entity\EntityInterface $entity){
    if ($entity->getEntityTypeId() === "taxonomy_term") {
        //  Assign private as default for field_access_term
        $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
            ->loadByProperties(['name' => "Private", 'vid' => 'islandora_access']);
        $term = reset($term);
        $term_id = $term->id();

        $field_config_ids = \Drupal::entityQuery('field_config')
            ->accessCheck(FALSE)
            ->condition('field_type', 'entity_reference')
            ->condition('status', 1)
            ->execute();
        foreach ($field_config_ids as $field_id => $field_name) {
            if (strpos($field_id, 'field_access_terms') !== false) {
                $field_config = \Drupal\field\Entity\FieldConfig::load($field_id);
                $field_config->setDefaultValue($term_id);
                $field_config->save();
            }
        }
    }
}