<?php

/**
 * @file
 * Contains islandora_group_defaults.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_group_defaults_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_group_defaults module.
    case 'help.page.islandora_group_defaults':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Default config for Access controle with Group, Group Media') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function islandora_group_defaults_theme() {
  return [
    'islandora_group_defaults' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_modules_installed
 */
/*function islandora_group_defaults_modules_installed($modules) {
    if (in_array('islandora_group_defaults', $modules)) {
        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'collection_based']);
        $group_to_create->set('label', 'Public Collection');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();

        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'collection_based']);
        $group_to_create->set('label', 'Private Collection');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();

        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'role_based']);
        $group_to_create->set('label', 'Private');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();

        $group_to_create= \Drupal::entityTypeManager()->getStorage('group')->create(['type' => 'collection_based']);
        $group_to_create->set('label', 'Public');
        $group_to_create->setOwner(\Drupal\user\Entity\User::load(1));
        $group_to_create->save();
    }
}*/